#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           10

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# add-ons
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox='^1'
bspc rule -a telegram desktop='^10'


bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

nitrogen --restore
picom -f
